import { Metadata } from "next";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Geekify booking online",
  description: "Generated by create next app",
};

export default function layout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="public/favicon.ico"
          sizes="any"
          type="image/x-icon"
        />
      </Head>
      <body>
        booking online navbar
        {children}
      </body>
    </html>
  );
}