import { Metadata } from "next";
import Head from "next/head";
import Navbar from "../components/sharedComponents/Navbar/Navbar";
import Footer from "../components/sharedComponents/Footer/Footer";
import { Montserrat } from "next/font/google";
import BottomFooter from "../components/sharedComponents/BottomFooter/BottomFooter";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

export const metadata: Metadata = {
  title: "Geekify",
  description: "Generated by create next app",
};

export default function layout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="public/favicon.ico"
          sizes="any"
          type="image/x-icon"
        />
      </Head>
      <body className={montserrat.className}>
        <Navbar />
        {children}
        <Footer/>
        <BottomFooter/>
      </body>
    </html>
  );
}
