import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import {  Montserrat } from "next/font/google";
import { Providers } from "./rtk-state/provider";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});


export const metadata: Metadata = {
  title: "Geekify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="public/favicon.ico"
          sizes="any"
          type="image/x-icon"
        />
      </Head>
      <body className={montserrat.className}>
        <Providers>{children}</Providers>
        {/* <script src="https://cdn.afterpay.com/afterpay-1.0.min.js"></script> */}

        <script
          id="afterPayGeneralLibrary"
          src="https://js.afterpay.com/afterpay-1.x.js"
          defer
        ></script>

        <script
          id="afterPayProductionLibrary"
          src="https://portal.sandbox.afterpay.com/afterpay.js"
          defer
        ></script>
        

      </body>
    </html>
  );
}
